-- 0001: extensions and enum types
CREATE EXTENSION IF NOT EXISTS "pgcrypto";   -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "citext";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";    -- trigram search for global search

CREATE TYPE employee_status AS ENUM (
  'CANDIDATE','OFFER','APPROVED','PRE_ONBOARDING','ONBOARDING','ACTIVE','PROBATION','CONFIRMED',
  'TRANSFERRED','PROMOTED','RESIGNED','TERMINATED','CLEARANCE','FINAL_SETTLEMENT','ARCHIVED'
);
CREATE TYPE employment_type AS ENUM ('FULL_TIME','PART_TIME','CONTRACT','TEMPORARY','INTERN','DAILY_WAGE');
CREATE TYPE gender AS ENUM ('MALE','FEMALE','OTHER','UNSPECIFIED');
CREATE TYPE marital_status AS ENUM ('SINGLE','MARRIED','DIVORCED','WIDOWED','UNSPECIFIED');
CREATE TYPE probation_status AS ENUM ('NOT_APPLICABLE','ON_PROBATION','EXTENDED','CONFIRMED','FAILED');
CREATE TYPE document_type AS ENUM ('EMIRATES_ID','PASSPORT','VISA','LABOUR_CARD','INSURANCE','CONTRACT','DRIVING_LICENSE','CERTIFICATE','OTHER');
CREATE TYPE document_status AS ENUM ('VALID','EXPIRING','EXPIRED','MISSING','PENDING');
CREATE TYPE punch_direction AS ENUM ('IN','OUT','UNKNOWN');
CREATE TYPE verification_method AS ENUM ('FACE','FINGER','CARD','PIN','PALM','MANUAL','UNKNOWN');
CREATE TYPE event_source AS ENUM ('DEVICE_PUSH','VYOM_SYNC','GATEWAY','MANUAL','IMPORT','API');
CREATE TYPE day_status AS ENUM ('PRESENT','ABSENT','HALF_DAY','ON_LEAVE','WEEK_OFF','PUBLIC_HOLIDAY','MISSING_PUNCH','NOT_YET_JOINED','EXITED','UNSCHEDULED');
CREATE TYPE attendance_exception_type AS ENUM ('ABSENT','LATE','EARLY_LEAVE','MISSING_IN','MISSING_OUT','DUPLICATE_PUNCH','INVALID_PUNCH','EXCESSIVE_OT','UNAPPROVED_OT','WRONG_SHIFT','OUTSIDE_SITE','UNMAPPED_USER');
CREATE TYPE exception_status AS ENUM ('OPEN','IN_REVIEW','RESOLVED','DISMISSED');
CREATE TYPE shift_type AS ENUM ('FIXED','FLEXIBLE','SPLIT');
CREATE TYPE leave_request_status AS ENUM ('DRAFT','PENDING','APPROVED','REJECTED','CANCELLED');
CREATE TYPE overtime_request_status AS ENUM ('PENDING','APPROVED','REJECTED','CANCELLED');
CREATE TYPE timesheet_status AS ENUM ('DRAFT','GENERATED','SUBMITTED','APPROVED','LOCKED');
CREATE TYPE payroll_run_status AS ENUM ('DRAFT','CALCULATING','HR_REVIEW','FINANCE_REVIEW','MANAGEMENT_APPROVAL','APPROVED','LOCKED','BANK_WPS','PAID','CLOSED');
CREATE TYPE salary_component_kind AS ENUM ('EARNING','DEDUCTION');
CREATE TYPE calc_method AS ENUM ('FIXED','PERCENTAGE','PER_DAY','PER_HOUR','PER_MINUTE','FORMULA');
CREATE TYPE device_status AS ENUM ('ONLINE','OFFLINE','UNKNOWN','ERROR','DECOMMISSIONED');
CREATE TYPE workflow_instance_status AS ENUM ('PENDING','IN_PROGRESS','APPROVED','REJECTED','CANCELLED','COMPLETED');
CREATE TYPE workflow_task_status AS ENUM ('PENDING','APPROVED','REJECTED','SKIPPED','CANCELLED');
CREATE TYPE notification_channel AS ENUM ('IN_APP','EMAIL','TEAMS');
CREATE TYPE integration_status AS ENUM ('ACTIVE','DISABLED','ERROR');

-- Reusable trigger to maintain updated_at
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;
