'use client';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Wifi, WifiOff, Radio, HelpCircle } from 'lucide-react';
import { AppShell } from '@/components/layout/shell';
import { api } from '@/lib/api';
import { useAuth } from '@/lib/providers';
import { Alert, Badge, Card, EmptyState, Field, Modal, PageHeader, StatTile, Tabs } from '@/components/ui';
import { fmtDateTime } from '@/lib/format';

export default function Page() { return <AppShell><Devices /></AppShell>; }
function Devices() {
  const { can } = useAuth();
  const qc = useQueryClient();
  const [tab, setTab] = useState<'devices' | 'mappings' | 'integration'>('devices');
  const devices = useQuery({ queryKey: ['devices'], queryFn: () => api<any[]>('/api/v1/devices'), refetchInterval: 30_000 });
  const health = useQuery({ queryKey: ['devices', 'health'], queryFn: () => api<any>('/api/v1/devices/health'), refetchInterval: 30_000 });
  const [mq, setMq] = useState('');
  const mappings = useQuery({ queryKey: ['mappings', mq], queryFn: () => api<any[]>(`/api/v1/devices/mappings${mq ? `?q=${encodeURIComponent(mq)}` : ''}`), enabled: tab === 'mappings' });
  const caps = useQuery({ queryKey: ['integrations', 'caps'], queryFn: () => api<any>('/api/v1/integrations/biometric/capabilities'), enabled: tab === 'integration' && can('integrations:read') });
  const conns = useQuery({ queryKey: ['integrations'], queryFn: () => api<any[]>('/api/v1/integrations'), enabled: tab === 'integration' && can('integrations:read') });
  const [edit, setEdit] = useState<any | null>(null);
  const [map, setMap] = useState(false);
  const sites = useQuery({ queryKey: ['org', 'sites'], queryFn: () => api<any[]>('/api/v1/org/sites'), enabled: can('org:read') });
  const icon = (c: string) => c === 'ONLINE' ? <Wifi size={16} className="text-success" /> : c === 'STALE' ? <Radio size={16} className="text-warning" /> : c === 'OFFLINE' ? <WifiOff size={16} className="text-danger" /> : <HelpCircle size={16} className="text-muted" />;
  return (
    <>
      <PageHeader title="Devices & biometric integration" subtitle="Matrix ARGO FACE terminals. Devices match faces; Burtplace stores only user IDs and timestamps — never templates." actions={can('devices:write') && tab === 'devices' && <button className="btn-primary" onClick={() => setEdit({})}>Register device</button>} />
      {health.data && <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatTile label="Devices" value={health.data.total} /><StatTile label="Online" value={health.data.online} tone="success" /><StatTile label="Stale / offline" value={`${health.data.stale} / ${health.data.offline}`} tone={health.data.offline ? 'danger' : 'default'} /><StatTile label="Events today" value={health.data.eventsToday} /><StatTile label="Unmapped users" value={health.data.unmappedOpen} tone={health.data.unmappedOpen ? 'warning' : 'default'} hint="device IDs with no employee" /></div>}
      <Tabs tabs={[{ key: 'devices', label: 'Devices' }, { key: 'mappings', label: 'User mappings' }, ...(can('integrations:read') ? [{ key: 'integration' as const, label: 'Integration status' }] : [])]} value={tab} onChange={setTab} />
      {tab === 'devices' && <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{devices.data?.map((d) => <div key={d.id} className="card p-5"><div className="flex items-start justify-between"><div className="flex items-center gap-2">{icon(d.connection)}<div><h3 className="font-semibold">{d.name}</h3><p className="text-xs text-muted">{d.deviceCode} · {d.model ?? d.vendor}</p></div></div><Badge status={d.connection} /></div><dl className="mt-4 grid grid-cols-2 gap-x-3 gap-y-1.5 text-xs"><dt className="text-muted">Site</dt><dd>{d.siteName ?? '—'}</dd><dt className="text-muted">IP</dt><dd>{d.ipAddress ?? '—'}</dd><dt className="text-muted">Last seen</dt><dd>{fmtDateTime(d.lastSeenAt)}</dd><dt className="text-muted">Last punch</dt><dd>{fmtDateTime(d.lastPunchAt)}</dd><dt className="text-muted">Events today</dt><dd>{d.eventsToday}</dd><dt className="text-muted">Enrolled users</dt><dd>{d.enrolledUserCount ?? '—'}</dd><dt className="text-muted">Firmware</dt><dd>{d.firmwareVersion ?? '—'}</dd></dl>{d.lastError && <p className="mt-2 text-xs text-danger">{d.lastError}</p>}{can('devices:write') && <button className="btn-secondary btn-sm mt-4" onClick={() => setEdit(d)}>Edit</button>}</div>)}{devices.data?.length === 0 && <EmptyState title="No devices registered" />}</div>}
      {tab === 'mappings' && <Card padded={false} actions={can('devices:write') && <button className="btn-primary btn-sm" onClick={() => setMap(true)}>Map user</button>} title="Device user ID ↔ employee"><div className="border-b p-3"><input className="input sm:max-w-xs" placeholder="Search by device user id, employee no, name" value={mq} onChange={(e) => setMq(e.target.value)} /></div><table className="data"><thead><tr><th>Device user ID</th><th>Employee</th><th>Provider</th><th>Enrolled</th><th>Active</th></tr></thead><tbody>{mappings.data?.map((m) => <tr key={m.id}><td className="font-mono">{m.externalUserId}</td><td className="font-medium">{m.employeeNo} · {m.employeeName}</td><td>{m.provider}</td><td>{fmtDateTime(m.enrolledAt)}</td><td>{m.isActive ? '✓' : '—'}</td></tr>)}</tbody></table></Card>}
      {tab === 'integration' && <div className="space-y-4">{conns.data?.map((c) => <Card key={c.id} title={<span>{c.code} <Badge status={c.status === 'ACTIVE' ? 'ACTIVE' : c.status === 'ERROR' ? 'ERROR' : 'CANCELLED'} className="ms-2">{c.status}</Badge></span>}><dl className="grid grid-cols-2 gap-1 text-sm md:grid-cols-4"><dt className="text-muted">Provider</dt><dd>{c.provider}</dd><dt className="text-muted">Last success</dt><dd>{fmtDateTime(c.lastSuccessAt)}</dd><dt className="text-muted">Last error</dt><dd className="text-danger">{c.lastError ?? '—'}</dd><dt className="text-muted">Open failures</dt><dd>{c.openFailures}</dd></dl><p className="mt-2 font-mono text-xs text-muted">{JSON.stringify(c.config)}</p></Card>)}
        {caps.data && <Card title={`Active adapter: ${caps.data.provider ?? 'none'} · health ${caps.data.health.ok ? 'OK' : 'NOT READY'}`}>{!caps.data.health.ok && <div className="mb-3"><Alert tone="warning">{caps.data.health.message}</Alert></div>}<table className="data"><thead><tr><th>Capability</th><th>Status</th><th>Note</th></tr></thead><tbody>{Object.entries(caps.data.capabilities).map(([k, v]: any) => <tr key={k}><td className="font-medium">{k}</td><td><Badge status={v.status === 'OFFICIALLY_DOCUMENTED' ? 'ACTIVE' : v.status === 'VENDOR_SUPPORTED' ? 'LOCKED' : v.status === 'UNKNOWN' ? 'PENDING' : 'CANCELLED'}>{v.status.replace(/_/g, ' ')}</Badge></td><td className="text-xs text-muted">{v.note ?? ''}</td></tr>)}</tbody></table></Card>}</div>}
      <DeviceModal device={edit} sites={sites.data ?? []} onClose={() => setEdit(null)} onSaved={() => { qc.invalidateQueries({ queryKey: ['devices'] }); setEdit(null); }} />
      <MapModal open={map} onClose={() => setMap(false)} onSaved={() => { qc.invalidateQueries({ queryKey: ['mappings'] }); qc.invalidateQueries({ queryKey: ['devices'] }); setMap(false); }} />
    </>
  );
}
function DeviceModal({ device, sites, onClose, onSaved }: any) {
  const [f, setF] = useState<any>(device ?? {});
  const m = useMutation({ mutationFn: () => { const body = { deviceCode: f.deviceCode, name: f.name, model: f.model || null, ipAddress: f.ipAddress || null, siteId: f.siteId || null, enrolledUserCount: f.enrolledUserCount ?? null }; return f.id ? api(`/api/v1/devices/${f.id}`, { method: 'PATCH', json: body }) : api('/api/v1/devices', { method: 'POST', json: { ...body, vendor: 'MATRIX' } }); }, onSuccess: onSaved });
  if (!device) return null;
  return <Modal open onClose={onClose} title={f.id ? `Edit ${device.deviceCode}` : 'Register device'}><div className="space-y-3"><Field label="Device code / serial"><input className="input" value={f.deviceCode ?? ''} onChange={(e) => setF({ ...f, deviceCode: e.target.value })} /></Field><Field label="Name"><input className="input" value={f.name ?? ''} onChange={(e) => setF({ ...f, name: e.target.value })} /></Field><Field label="Model"><input className="input" value={f.model ?? 'ARGO FACE'} onChange={(e) => setF({ ...f, model: e.target.value })} /></Field><Field label="IP address"><input className="input" value={f.ipAddress ?? ''} onChange={(e) => setF({ ...f, ipAddress: e.target.value })} /></Field><Field label="Site"><select className="input" value={f.siteId ?? ''} onChange={(e) => setF({ ...f, siteId: e.target.value })}><option value="">—</option>{sites.map((s: any) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>{m.error && <Alert tone="danger">{(m.error as Error).message}</Alert>}<div className="flex justify-end gap-2"><button className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={m.isPending} onClick={() => m.mutate()}>Save</button></div></div></Modal>;
}
function MapModal({ open, onClose, onSaved }: any) {
  const [f, setF] = useState({ employeeNo: '', externalUserId: '' });
  const m = useMutation({ mutationFn: async () => { const e = await api<any>(`/api/v1/employees/by-number/${f.employeeNo}`); return api<any>('/api/v1/devices/mappings', { method: 'POST', json: { employeeId: e.id, externalUserId: f.externalUserId } }); }, onSuccess: onSaved });
  return <Modal open={open} onClose={onClose} title="Map device user to employee"><div className="space-y-3"><Field label="Device user ID (Matrix)"><input className="input" value={f.externalUserId} onChange={(e) => setF({ ...f, externalUserId: e.target.value })} /></Field><Field label="Employee number"><input className="input" placeholder="BP-26-777" value={f.employeeNo} onChange={(e) => setF({ ...f, employeeNo: e.target.value })} /></Field><Alert tone="info">Any raw punches already received for this device user are linked to the employee and re-processed automatically.</Alert>{m.error && <Alert tone="danger">{(m.error as Error).message}</Alert>}<div className="flex justify-end gap-2"><button className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={m.isPending} onClick={() => m.mutate()}>Map</button></div></div></Modal>;
}
