'use client';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AppShell } from '@/components/layout/shell';
import { api } from '@/lib/api';
import { useAuth } from '@/lib/providers';
import { Alert, Badge, Card, EmptyState, Field, Modal, PageHeader, Tabs } from '@/components/ui';
import { fmtDate } from '@/lib/format';

type Tab = 'departments' | 'sites' | 'projects' | 'designations' | 'holidays';
export default function Page() { return <AppShell><Organization /></AppShell>; }
function Organization() {
  const { can } = useAuth();
  const qc = useQueryClient();
  const [tab, setTab] = useState<Tab>('departments');
  const depts = useQuery({ queryKey: ['org', 'departments'], queryFn: () => api<any[]>('/api/v1/org/departments') });
  const sites = useQuery({ queryKey: ['org', 'sites'], queryFn: () => api<any[]>('/api/v1/org/sites') });
  const projects = useQuery({ queryKey: ['org', 'projects'], queryFn: () => api<any[]>('/api/v1/org/projects') });
  const desigs = useQuery({ queryKey: ['org', 'designations'], queryFn: () => api<any[]>('/api/v1/org/designations') });
  const holidays = useQuery({ queryKey: ['org', 'holidays'], queryFn: () => api<any[]>('/api/v1/org/holidays') });
  const [modal, setModal] = useState<Tab | null>(null);
  const [form, setForm] = useState<any>({});
  const endpoint: Record<Tab, string> = { departments: '/api/v1/org/departments', sites: '/api/v1/org/sites', projects: '/api/v1/org/projects', designations: '/api/v1/org/designations', holidays: '/api/v1/org/holidays' };
  const m = useMutation({ mutationFn: () => api(endpoint[modal!], { method: 'POST', json: Object.fromEntries(Object.entries(form).filter(([, v]) => v !== '')) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['org'] }); setModal(null); setForm({}); } });
  const write = can('org:write');
  return (
    <>
      <PageHeader title="Organization" subtitle="Departments, sites, projects and designations are the backbone of costing and access scoping." actions={write && <button className="btn-primary" onClick={() => { setForm({}); setModal(tab); }}>New {tab.slice(0, -1)}</button>} />
      <Tabs tabs={[{ key: 'departments', label: 'Departments', count: depts.data?.length }, { key: 'sites', label: 'Sites', count: sites.data?.length }, { key: 'projects', label: 'Projects', count: projects.data?.length }, { key: 'designations', label: 'Designations', count: desigs.data?.length }, { key: 'holidays', label: 'Holidays', count: holidays.data?.length }]} value={tab} onChange={setTab} />
      {tab === 'departments' && <Card padded={false}><table className="data"><thead><tr><th>Code</th><th>Name</th><th>Arabic</th><th>Headcount</th><th>Active</th></tr></thead><tbody>{depts.data?.map((d) => <tr key={d.id}><td className="font-mono text-xs">{d.code}</td><td className="font-medium">{d.name}</td><td dir="rtl" className="text-start">{d.nameAr ?? '—'}</td><td>{d.headcount}</td><td>{d.isActive ? '✓' : '—'}</td></tr>)}</tbody></table></Card>}
      {tab === 'sites' && <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{sites.data?.map((s) => <div key={s.id} className="card p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted">{s.code} · {s.siteType}</p><h3 className="font-semibold">{s.name}</h3></div><Badge status={s.isActive ? 'ACTIVE' : 'CANCELLED'}>{s.isActive ? 'Active' : 'Inactive'}</Badge></div><p className="mt-1 text-xs text-muted">{s.projectCode ? `Project ${s.projectCode} · ` : ''}{s.emirate ?? ''} · {s.timezone}</p><div className="mt-4 flex gap-6 text-sm"><div><p className="text-2xl font-semibold">{s.headcount}</p><p className="text-xs text-muted">employees</p></div><div><p className="text-2xl font-semibold">{s.deviceCount}</p><p className="text-xs text-muted">devices</p></div></div></div>)}</div>}
      {tab === 'projects' && <Card padded={false}><table className="data"><thead><tr><th>Code</th><th>Name</th><th>Client</th><th>Manager</th><th>Sites</th><th>Headcount</th><th>Status</th></tr></thead><tbody>{projects.data?.map((p) => <tr key={p.id}><td className="font-mono text-xs">{p.code}</td><td className="font-medium">{p.name}</td><td>{p.clientName ?? '—'}</td><td>{p.managerName ?? '—'}</td><td>{p.siteCount}</td><td>{p.headcount}</td><td><Badge status={p.status} /></td></tr>)}</tbody></table></Card>}
      {tab === 'designations' && <Card padded={false}><table className="data"><thead><tr><th>Code</th><th>Title</th><th>Arabic</th><th>Grade</th></tr></thead><tbody>{desigs.data?.map((d) => <tr key={d.id}><td className="font-mono text-xs">{d.code}</td><td className="font-medium">{d.title}</td><td dir="rtl" className="text-start">{d.titleAr ?? '—'}</td><td>{d.grade ?? '—'}</td></tr>)}</tbody></table></Card>}
      {tab === 'holidays' && <Card padded={false}>{holidays.data?.length ? <table className="data"><thead><tr><th>Date</th><th>Name</th><th>Until</th><th>Paid</th><th>Scope</th><th></th></tr></thead><tbody>{holidays.data.map((h) => <tr key={h.id}><td className="font-medium">{fmtDate(h.holidayDate)}</td><td>{h.name}</td><td>{fmtDate(h.endDate)}</td><td>{h.isPaid ? '✓' : '—'}</td><td className="text-muted">{h.appliesToSiteId ? 'site' : 'company'}</td><td className="text-end">{write && <button className="btn-ghost btn-sm text-danger" onClick={() => confirm('Delete holiday?') && api(`/api/v1/org/holidays/${h.id}`, { method: 'DELETE' }).then(() => qc.invalidateQueries({ queryKey: ['org', 'holidays'] }))}>Delete</button>}</td></tr>)}</tbody></table> : <EmptyState />}<p className="p-3 text-xs text-muted">Religious holiday dates depend on moon sighting and must be confirmed each year.</p></Card>}
      <Modal open={!!modal} onClose={() => setModal(null)} title={`New ${modal?.slice(0, -1)}`}><div className="space-y-3">
        {modal === 'holidays' ? <><Field label="Name"><input className="input" value={form.name ?? ''} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><div className="grid grid-cols-2 gap-3"><Field label="Date"><input type="date" className="input" value={form.holidayDate ?? ''} onChange={(e) => setForm({ ...form, holidayDate: e.target.value })} /></Field><Field label="End date (optional)"><input type="date" className="input" value={form.endDate ?? ''} onChange={(e) => setForm({ ...form, endDate: e.target.value })} /></Field></div></> : <><Field label="Code"><input className="input" value={form.code ?? ''} onChange={(e) => setForm({ ...form, code: e.target.value.toUpperCase() })} /></Field><Field label={modal === 'designations' ? 'Title' : 'Name'}><input className="input" value={(modal === 'designations' ? form.title : form.name) ?? ''} onChange={(e) => setForm({ ...form, [modal === 'designations' ? 'title' : 'name']: e.target.value })} /></Field><Field label="Arabic"><input className="input" dir="rtl" value={(modal === 'designations' ? form.titleAr : form.nameAr) ?? ''} onChange={(e) => setForm({ ...form, [modal === 'designations' ? 'titleAr' : 'nameAr']: e.target.value })} /></Field>{modal === 'sites' && <><Field label="Type"><select className="input" value={form.siteType ?? 'SITE'} onChange={(e) => setForm({ ...form, siteType: e.target.value })}>{['OFFICE', 'SITE', 'CAMP', 'WAREHOUSE'].map((t) => <option key={t}>{t}</option>)}</select></Field><Field label="Project"><select className="input" value={form.projectId ?? ''} onChange={(e) => setForm({ ...form, projectId: e.target.value })}><option value="">—</option>{projects.data?.map((p) => <option key={p.id} value={p.id}>{p.code} {p.name}</option>)}</select></Field><Field label="Emirate"><input className="input" value={form.emirate ?? ''} onChange={(e) => setForm({ ...form, emirate: e.target.value })} /></Field></>}{modal === 'designations' && <Field label="Grade"><input className="input" value={form.grade ?? ''} onChange={(e) => setForm({ ...form, grade: e.target.value })} /></Field>}{modal === 'projects' && <Field label="Client"><input className="input" value={form.clientName ?? ''} onChange={(e) => setForm({ ...form, clientName: e.target.value })} /></Field>}</>}
        {m.error && <Alert tone="danger">{(m.error as Error).message}</Alert>}<div className="flex justify-end gap-2"><button className="btn-secondary" onClick={() => setModal(null)}>Cancel</button><button className="btn-primary" disabled={m.isPending} onClick={() => m.mutate()}>Create</button></div></div></Modal>
    </>
  );
}
