'use client';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AppShell } from '@/components/layout/shell';
import { api } from '@/lib/api';
import { useAuth } from '@/lib/providers';
import { Alert, Badge, Card, EmptyState, Field, Modal, PageHeader, Tabs } from '@/components/ui';
import { fmtDate, fmtMinutes } from '@/lib/format';

type Tab = 'shifts' | 'patterns' | 'assignments';
export default function Page() { return <AppShell><Shifts /></AppShell>; }
const DOW = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

function Shifts() {
  const { can } = useAuth();
  const qc = useQueryClient();
  const [tab, setTab] = useState<Tab>('shifts');
  const shifts = useQuery({ queryKey: ['shifts'], queryFn: () => api<any[]>('/api/v1/shifts') });
  const patterns = useQuery({ queryKey: ['work-patterns'], queryFn: () => api<any[]>('/api/v1/shifts/work-patterns') });
  const assignments = useQuery({ queryKey: ['assignments'], queryFn: () => api<any[]>('/api/v1/shifts/assignments') });
  const sites = useQuery({ queryKey: ['org', 'sites'], queryFn: () => api<any[]>('/api/v1/org/sites'), enabled: can('org:read') });
  const [edit, setEdit] = useState<any | null>(null);
  const [assign, setAssign] = useState(false);
  const siteName = (id: string | null) => sites.data?.find((s) => s.id === id)?.name ?? id;
  return (
    <>
      <PageHeader title="Shifts & schedules" subtitle="Grace, breaks, overtime thresholds and rounding are configuration, never code." actions={<>{can('shifts:write') && tab === 'shifts' && <button className="btn-primary" onClick={() => setEdit({})}>New shift</button>}{can('shifts:assign') && tab === 'assignments' && <button className="btn-primary" onClick={() => setAssign(true)}>New assignment</button>}</>} />
      <Tabs tabs={[{ key: 'shifts', label: 'Shifts', count: shifts.data?.length }, { key: 'patterns', label: 'Work patterns', count: patterns.data?.length }, { key: 'assignments', label: 'Assignments', count: assignments.data?.length }]} value={tab} onChange={setTab} />
      {tab === 'shifts' && <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{shifts.data?.map((s) => <div key={s.id} className="card p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted">{s.code}</p><h3 className="text-lg font-semibold">{s.name}</h3></div><Badge status={s.isActive ? 'ACTIVE' : 'CANCELLED'}>{s.isActive ? 'Active' : 'Inactive'}</Badge></div><p className="mt-3 text-3xl font-semibold tabular-nums tracking-tight">{s.startTime} <span className="text-muted">→</span> {s.endTime}{s.crossesMidnight && <span className="ms-2 text-xs text-warning">+1 day</span>}</p><dl className="mt-4 grid grid-cols-2 gap-x-4 gap-y-2 text-xs"><dt className="text-muted">Required</dt><dd>{fmtMinutes(s.requiredMinutes)}</dd><dt className="text-muted">Break</dt><dd>{fmtMinutes(s.breakMinutes)} {s.breakIsPaid ? '(paid)' : '(unpaid)'}</dd><dt className="text-muted">Grace in / out</dt><dd>{s.graceInMinutes}m / {s.graceOutMinutes}m</dd><dt className="text-muted">Half day below</dt><dd>{s.halfDayThresholdMinutes ? fmtMinutes(s.halfDayThresholdMinutes) : '—'}</dd><dt className="text-muted">OT</dt><dd>{s.otEnabled ? `after ${fmtMinutes(s.otAfterMinutes ?? s.requiredMinutes)}, min ${s.otMinBlockMinutes}m, round ${s.otRoundingMinutes}m, max ${s.otMaxMinutesPerDay ? fmtMinutes(s.otMaxMinutesPerDay) : '∞'}` : 'disabled'}</dd><dt className="text-muted">OT approval</dt><dd>{s.otRequiresApproval ? 'required' : 'automatic'}</dd></dl>{can('shifts:write') && <button className="btn-secondary btn-sm mt-4" onClick={() => setEdit(s)}>Edit rules</button>}</div>)}</div>}
      {tab === 'patterns' && <div className="grid gap-4 md:grid-cols-2">{patterns.data?.map((p) => <div key={p.id} className="card p-5"><p className="text-xs font-semibold uppercase tracking-wider text-muted">{p.code}</p><h3 className="text-lg font-semibold">{p.name}</h3><div className="mt-3 flex gap-1">{DOW.map((d, i) => <span key={d} className={`flex h-9 w-11 items-center justify-center rounded-lg text-xs font-medium ${p.weekOffs.includes(i) ? 'bg-surface-2 text-muted line-through' : 'bg-brand-soft text-brand'}`}>{d}</span>)}</div><p className="mt-3 text-xs text-muted">Default shift: {shifts.data?.find((s) => s.id === p.defaultShiftId)?.name ?? '—'}{Object.keys(p.weekdayShifts).length ? ` · overrides: ${Object.entries(p.weekdayShifts).map(([d, sid]) => `${DOW[Number(d)]}=${shifts.data?.find((s) => s.id === sid)?.code}`).join(', ')}` : ''}</p></div>)}</div>}
      {tab === 'assignments' && <Card padded={false}>{assignments.data?.length ? <table className="data"><thead><tr><th>Scope</th><th>Target</th><th>Pattern / shift</th><th>From</th><th>To</th><th>Priority</th><th></th></tr></thead><tbody>{assignments.data.map((a) => <tr key={a.id}><td><Badge>{a.scope}</Badge></td><td className="font-medium">{a.scope === 'SITE' ? siteName(a.siteId) : a.scope === 'PROJECT' ? a.projectId : <a className="hover:underline" href={`/employees/${a.employeeId}`}>{a.employeeId?.slice(0, 8)}…</a>}</td><td>{patterns.data?.find((p) => p.id === a.workPatternId)?.name ?? shifts.data?.find((s) => s.id === a.shiftId)?.name ?? '—'}</td><td>{fmtDate(a.effectiveFrom)}</td><td>{fmtDate(a.effectiveTo)}</td><td>{a.priority}</td><td className="text-end">{can('shifts:assign') && <button className="btn-ghost btn-sm text-danger" onClick={() => confirm('End this assignment?') && api(`/api/v1/shifts/assignments/${a.id}`, { method: 'DELETE' }).then(() => qc.invalidateQueries({ queryKey: ['assignments'] }))}>End</button>}</td></tr>)}</tbody></table> : <EmptyState />}</Card>}
      <ShiftModal shift={edit} onClose={() => setEdit(null)} onSaved={() => { qc.invalidateQueries({ queryKey: ['shifts'] }); setEdit(null); }} />
      <AssignModal open={assign} onClose={() => setAssign(false)} shifts={shifts.data ?? []} patterns={patterns.data ?? []} sites={sites.data ?? []} onSaved={() => { qc.invalidateQueries({ queryKey: ['assignments'] }); setAssign(false); }} />
    </>
  );
}
function ShiftModal({ shift, onClose, onSaved }: { shift: any | null; onClose: () => void; onSaved: () => void }) {
  const [f, setF] = useState<any>(shift ?? {});
  const isNew = !shift?.id;
  const m = useMutation({ mutationFn: () => { const { id, crossesMidnight, ...body } = f; return isNew ? api('/api/v1/shifts', { method: 'POST', json: body }) : api(`/api/v1/shifts/${id}`, { method: 'PATCH', json: body }); }, onSuccess: onSaved });
  if (!shift) return null;
  const num = (k: string, label: string) => <Field label={label}><input type="number" className="input" value={f[k] ?? ''} onChange={(e) => setF({ ...f, [k]: e.target.value === '' ? null : Number(e.target.value) })} /></Field>;
  const bool = (k: string, label: string) => <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!f[k]} onChange={(e) => setF({ ...f, [k]: e.target.checked })} />{label}</label>;
  return <Modal open onClose={onClose} title={isNew ? 'New shift' : `Edit ${shift.code}`} wide><div className="grid gap-3 sm:grid-cols-3"><Field label="Code"><input className="input" value={f.code ?? ''} onChange={(e) => setF({ ...f, code: e.target.value })} /></Field><Field label="Name" className="sm:col-span-2"><input className="input" value={f.name ?? ''} onChange={(e) => setF({ ...f, name: e.target.value })} /></Field><Field label="Start"><input type="time" className="input" value={f.startTime ?? '06:00'} onChange={(e) => setF({ ...f, startTime: e.target.value })} /></Field><Field label="End" hint="End ≤ start = crosses midnight"><input type="time" className="input" value={f.endTime ?? '17:00'} onChange={(e) => setF({ ...f, endTime: e.target.value })} /></Field>{num('requiredMinutes', 'Required minutes')}{num('breakMinutes', 'Break minutes')}{num('graceInMinutes', 'Grace in (min)')}{num('graceOutMinutes', 'Grace out (min)')}{num('halfDayThresholdMinutes', 'Half day below (min)')}{num('absentThresholdMinutes', 'Absent at/below (min)')}{num('otAfterMinutes', 'OT after (min, blank = required)')}{num('otMinBlockMinutes', 'OT min block')}{num('otRoundingMinutes', 'OT rounding')}{num('otMaxMinutesPerDay', 'OT max / day')}{num('earlyInWindowMinutes', 'Early-in window')}{num('lateOutWindowMinutes', 'Late-out window')}<div className="space-y-2 sm:col-span-3">{bool('otEnabled', 'Overtime enabled')}{bool('otRequiresApproval', 'Overtime requires approval')}{bool('countEarlyInAsOt', 'Count early arrival as overtime')}{bool('breakIsPaid', 'Break is paid')}</div></div>{m.error && <div className="mt-3"><Alert tone="danger">{(m.error as Error).message}</Alert></div>}<div className="mt-4 flex justify-end gap-2"><button className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={m.isPending} onClick={() => m.mutate()}>Save</button></div></Modal>;
}
function AssignModal({ open, onClose, shifts, patterns, sites, onSaved }: any) {
  const [f, setF] = useState<any>({ scope: 'EMPLOYEE', employeeNo: '', siteId: '', workPatternId: '', shiftId: '', effectiveFrom: new Date().toISOString().slice(0, 10), effectiveTo: '' });
  const m = useMutation({ mutationFn: async () => { let employeeId: string | undefined; if (f.scope === 'EMPLOYEE') { const e = await api<any>(`/api/v1/employees/by-number/${f.employeeNo}`); employeeId = e.id; } return api('/api/v1/shifts/assignments', { method: 'POST', json: { employeeId, siteId: f.scope === 'SITE' ? f.siteId : undefined, workPatternId: f.workPatternId || undefined, shiftId: f.shiftId || undefined, effectiveFrom: f.effectiveFrom, effectiveTo: f.effectiveTo || undefined } }); }, onSuccess: onSaved });
  return <Modal open={open} onClose={onClose} title="Assign schedule"><div className="space-y-3"><Field label="Scope"><select className="input" value={f.scope} onChange={(e) => setF({ ...f, scope: e.target.value })}><option value="EMPLOYEE">Employee (exception)</option><option value="SITE">Site (default for everyone at the site)</option></select></Field>{f.scope === 'EMPLOYEE' ? <Field label="Employee number"><input className="input" placeholder="BP-26-777" value={f.employeeNo} onChange={(e) => setF({ ...f, employeeNo: e.target.value })} /></Field> : <Field label="Site"><select className="input" value={f.siteId} onChange={(e) => setF({ ...f, siteId: e.target.value })}><option value="">—</option>{sites.map((s: any) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>}<Field label="Work pattern"><select className="input" value={f.workPatternId} onChange={(e) => setF({ ...f, workPatternId: e.target.value })}><option value="">—</option>{patterns.map((p: any) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Or a single shift every working day"><select className="input" value={f.shiftId} onChange={(e) => setF({ ...f, shiftId: e.target.value })}><option value="">—</option>{shifts.map((s: any) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="From"><input type="date" className="input" value={f.effectiveFrom} onChange={(e) => setF({ ...f, effectiveFrom: e.target.value })} /></Field><Field label="To (optional)"><input type="date" className="input" value={f.effectiveTo} onChange={(e) => setF({ ...f, effectiveTo: e.target.value })} /></Field></div>{m.error && <Alert tone="danger">{(m.error as Error).message}</Alert>}<div className="flex justify-end gap-2"><button className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={m.isPending} onClick={() => m.mutate()}>Assign</button></div></div></Modal>;
}
