'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus, Laptop } from 'lucide-react';
import { AppShell } from '@/components/layout/shell';
import { api, qs, type Paginated } from '@/lib/api';
import { useAuth } from '@/lib/providers';
import { Badge, Card, EmptyState, Field, Modal, PageHeader, Pagination, StatTile, TableSkeleton } from '@/components/ui';
import { fmtDate, humanStatus } from '@/lib/format';

export default function Page() { return <AppShell><Assets /></AppShell>; }

function Assets() {
  const { can, principal } = useAuth();
  const qc = useQueryClient();
  const [f, setF] = useState({ q: '', category: '', assigned: '', page: 1 });
  const list = useQuery({ queryKey: ['assets', 'list', f], queryFn: () => api<Paginated<any>>(`/api/v1/assets${qs({ ...f, pageSize: 25 })}`), enabled: can('assets:read'), placeholderData: (p) => p });
  const mine = useQuery({ queryKey: ['assets', principal?.employeeId], queryFn: () => api<any[]>(`/api/v1/assets/employee/${principal!.employeeId}`), enabled: !can('assets:read') && !!principal?.employeeId });
  const [create, setCreate] = useState<any | null>(null);
  const [assign, setAssign] = useState<any | null>(null);
  const [ret, setRet] = useState<any | null>(null);
  const [empQ, setEmpQ] = useState('');
  const emps = useQuery({ queryKey: ['employees', 'pick', empQ], queryFn: () => api<Paginated<any>>(`/api/v1/employees${qs({ q: empQ, pageSize: 8, working: true })}`), enabled: !!assign && empQ.length >= 2 });
  const inv = () => qc.invalidateQueries({ queryKey: ['assets'] });
  const mCreate = useMutation({ mutationFn: () => api('/api/v1/assets', { method: 'POST', json: Object.fromEntries(Object.entries(create).filter(([, v]) => v !== '')) }), onSuccess: () => { setCreate(null); inv(); } });
  const mAssign = useMutation({ mutationFn: (employeeId: string) => api(`/api/v1/assets/${assign.id}/assign`, { method: 'POST', json: { employeeId, conditionOut: assign.conditionOut || undefined } }), onSuccess: () => { setAssign(null); setEmpQ(''); inv(); } });
  const mReturn = useMutation({ mutationFn: () => api(`/api/v1/assets/${ret.id}/return`, { method: 'POST', json: { conditionIn: ret.conditionIn || undefined, damaged: !!ret.damaged } }), onSuccess: () => { setRet(null); inv(); } });
  if (!can('assets:read')) return <><PageHeader eyebrow="Assets" title="My assets" subtitle="Company property assigned to you. Return everything through your manager during clearance." />{mine.isLoading ? <TableSkeleton /> : mine.data?.length ? <Card padded={false}><table className="data"><thead><tr><th>Tag</th><th>Asset</th><th>Category</th><th>Assigned</th><th>Returned</th></tr></thead><tbody>{mine.data.map((a) => <tr key={a.id}><td className="font-mono text-xs">{a.assetTag}</td><td className="font-medium">{a.name}</td><td>{humanStatus(a.category)}</td><td>{fmtDate(a.assignedAt)}</td><td>{a.returnedAt ? fmtDate(a.returnedAt) : <Badge status="ACTIVE">In use</Badge>}</td></tr>)}</tbody></table></Card> : <EmptyState title="No assets assigned" />}</>;
  const rows = list.data?.data ?? [];
  return (
    <>
      <PageHeader eyebrow="Assets" title="Asset register" subtitle="Laptops, phones, vehicles, tools and PPE — who holds what, and returns during clearance. Damage on return can become a deduction request." actions={can('assets:write') && <button className="btn-primary" onClick={() => setCreate({ assetTag: '', category: 'LAPTOP', name: '', serialNumber: '', purchaseDate: '', notes: '' })}><Plus size={16} />Register asset</button>} />
      <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatTile label="Registered" value={list.data?.meta.total ?? '—'} icon={<Laptop size={18} />} /><StatTile label="Assigned (this page)" value={rows.filter((a) => a.holder).length} tone="info" /><StatTile label="Available (this page)" value={rows.filter((a) => !a.holder && a.status !== 'DAMAGED').length} tone="success" /><StatTile label="Damaged (this page)" value={rows.filter((a) => a.status === 'DAMAGED').length} tone="warning" /></div>
      <Card padded={false}>
        <div className="flex flex-wrap gap-2 border-b p-3"><input className="input sm:max-w-xs" placeholder="Search tag, name, serial…" value={f.q} onChange={(e) => setF({ ...f, q: e.target.value, page: 1 })} /><select className="input sm:w-40" value={f.category} onChange={(e) => setF({ ...f, category: e.target.value, page: 1 })}><option value="">All categories</option>{['LAPTOP', 'PHONE', 'VEHICLE', 'TOOL', 'PPE', 'ACCESS_CARD', 'OTHER'].map((c) => <option key={c} value={c}>{humanStatus(c)}</option>)}</select><select className="input sm:w-40" value={f.assigned} onChange={(e) => setF({ ...f, assigned: e.target.value, page: 1 })}><option value="">Assigned & free</option><option value="true">Assigned</option><option value="false">Available</option></select></div>
        {list.isLoading ? <TableSkeleton /> : rows.length ? <div className="overflow-x-auto"><table className="data"><thead><tr><th>Tag</th><th>Asset</th><th>Category</th><th>Serial</th><th>Site</th><th>Status</th><th>Holder</th><th></th></tr></thead><tbody>{rows.map((a) => <tr key={a.id}><td className="font-mono text-xs">{a.assetTag}</td><td className="font-medium">{a.name}</td><td>{humanStatus(a.category)}</td><td className="text-xs text-muted">{a.serialNumber ?? '—'}</td><td>{a.site ?? '—'}</td><td><Badge status={a.status === 'ASSIGNED' ? 'IN_PROGRESS' : a.status === 'AVAILABLE' ? 'ACTIVE' : a.status === 'DAMAGED' ? 'HIGH' : a.status}>{humanStatus(a.status)}</Badge></td><td>{a.holder ? <Link href={`/employees/${a.holder.id}?tab=assets`} className="hover:underline">{a.holder.name}<span className="block text-[11px] text-muted">{a.holder.employeeNo} · since {fmtDate(a.holder.assignedAt)}</span></Link> : <span className="text-muted">—</span>}</td><td className="whitespace-nowrap">{can('assets:write') && (a.holder ? <button className="btn-ghost btn-sm" onClick={() => setRet({ id: a.id, name: a.name, conditionIn: '', damaged: false })}>Return</button> : <button className="btn-ghost btn-sm" onClick={() => setAssign({ id: a.id, name: a.name, conditionOut: '' })}>Assign</button>)}</td></tr>)}</tbody></table></div> : <EmptyState hint="Register the first asset." />}
        {list.data && <Pagination page={list.data.meta.page} totalPages={list.data.meta.totalPages} total={list.data.meta.total} onPage={(p) => setF({ ...f, page: p })} />}
      </Card>
      <Modal open={!!create} onClose={() => setCreate(null)} title="Register asset">{create && <div className="grid gap-3 sm:grid-cols-2"><Field label="Asset tag"><input className="input" value={create.assetTag} onChange={(e) => setCreate({ ...create, assetTag: e.target.value.toUpperCase() })} /></Field><Field label="Category"><select className="input" value={create.category} onChange={(e) => setCreate({ ...create, category: e.target.value })}>{['LAPTOP', 'PHONE', 'VEHICLE', 'TOOL', 'PPE', 'ACCESS_CARD', 'OTHER'].map((c) => <option key={c} value={c}>{humanStatus(c)}</option>)}</select></Field><Field label="Name" className="sm:col-span-2"><input className="input" value={create.name} onChange={(e) => setCreate({ ...create, name: e.target.value })} /></Field><Field label="Serial number"><input className="input" value={create.serialNumber} onChange={(e) => setCreate({ ...create, serialNumber: e.target.value })} /></Field><Field label="Purchase date"><input type="date" className="input" value={create.purchaseDate} onChange={(e) => setCreate({ ...create, purchaseDate: e.target.value })} /></Field><Field label="Notes" className="sm:col-span-2"><input className="input" value={create.notes} onChange={(e) => setCreate({ ...create, notes: e.target.value })} /></Field><div className="flex justify-end sm:col-span-2"><button className="btn-primary" disabled={!create.assetTag || !create.name} onClick={() => mCreate.mutate()}>Register</button></div></div>}</Modal>
      <Modal open={!!assign} onClose={() => setAssign(null)} title={assign ? `Assign ${assign.name}` : ''}>{assign && <div className="space-y-3"><Field label="Condition at hand-over"><input className="input" value={assign.conditionOut} onChange={(e) => setAssign({ ...assign, conditionOut: e.target.value })} /></Field><Field label="Employee"><input className="input" autoFocus placeholder="Type a name or employee number…" value={empQ} onChange={(e) => setEmpQ(e.target.value)} />{emps.data?.data.length ? <div className="mt-2 max-h-56 overflow-y-auto rounded-xl border">{emps.data.data.map((e) => <button key={e.id} className="flex w-full items-center justify-between px-3 py-2 text-start text-sm hover:bg-brand-soft/60" onClick={() => mAssign.mutate(e.id)}><span>{e.fullNameEn}</span><span className="text-xs text-muted">{e.employeeNo} · {e.site?.name ?? '—'}</span></button>)}</div> : null}</Field></div>}</Modal>
      <Modal open={!!ret} onClose={() => setRet(null)} title={ret ? `Return ${ret.name}` : ''}>{ret && <div className="space-y-3"><Field label="Condition on return"><input className="input" value={ret.conditionIn} onChange={(e) => setRet({ ...ret, conditionIn: e.target.value })} /></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={ret.damaged} onChange={(e) => setRet({ ...ret, damaged: e.target.checked })} />Damaged — raise an asset-damage deduction from the employee profile afterwards</label><div className="flex justify-end"><button className="btn-primary" onClick={() => mReturn.mutate()}>Confirm return</button></div></div>}</Modal>
    </>
  );
}
