'use client';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { AppShell } from '@/components/layout/shell';
import { api, qs, type Paginated } from '@/lib/api';
import { useAuth } from '@/lib/providers';
import { Badge, Card, EmptyState, PageHeader, Pagination, TableSkeleton, Tabs } from '@/components/ui';
import { fmtDateTime } from '@/lib/format';

export default function Page() { return <AppShell><Settings /></AppShell>; }
function Settings() {
  const { can } = useAuth();
  const [tab, setTab] = useState<'audit' | 'integrations' | 'workflows' | 'recon'>(can('audit:read') ? 'audit' : 'integrations');
  const [f, setF] = useState({ entityType: '', action: '', page: 1 });
  const audit = useQuery({ queryKey: ['audit', f], queryFn: () => api<Paginated<any>>(`/api/v1/audit${qs({ ...f, pageSize: 50 })}`), enabled: tab === 'audit' && can('audit:read'), placeholderData: (p) => p });
  const logs = useQuery({ queryKey: ['integrations', 'logs'], queryFn: () => api<any>('/api/v1/integrations/logs'), enabled: tab === 'integrations' && can('integrations:read') });
  const wf = useQuery({ queryKey: ['workflows', 'definitions'], queryFn: () => api<any[]>('/api/v1/workflows/definitions'), enabled: tab === 'workflows' && can('workflows:read') });
  const recon = useQuery({ queryKey: ['recon'], queryFn: () => api<any>('/api/v1/attendance/reconcile/latest'), enabled: tab === 'recon' && can('attendance:read') });
  return (
    <>
      <PageHeader title="Settings & system" subtitle="Audit trail, integrations, workflow definitions and reconciliation." />
      <Tabs tabs={[...(can('audit:read') ? [{ key: 'audit' as const, label: 'Audit trail' }] : []), ...(can('integrations:read') ? [{ key: 'integrations' as const, label: 'Integration logs' }] : []), ...(can('workflows:read') ? [{ key: 'workflows' as const, label: 'Workflows' }] : []), ...(can('attendance:read') ? [{ key: 'recon' as const, label: 'Reconciliation' }] : [])]} value={tab} onChange={setTab} />
      {tab === 'audit' && <Card padded={false}><div className="flex gap-2 border-b p-3"><input className="input sm:w-48" placeholder="Entity type (employee…)" value={f.entityType} onChange={(e) => setF({ ...f, entityType: e.target.value, page: 1 })} /><input className="input sm:w-48" placeholder="Action prefix (payroll.…)" value={f.action} onChange={(e) => setF({ ...f, action: e.target.value, page: 1 })} /></div>{audit.isLoading ? <TableSkeleton /> : <div className="overflow-x-auto"><table className="data"><thead><tr><th>When</th><th>Actor</th><th>Action</th><th>Entity</th><th>Change</th><th>Reason</th><th>IP</th></tr></thead><tbody>{audit.data?.data.map((a) => <tr key={a.id}><td className="whitespace-nowrap">{fmtDateTime(a.occurredAt)}</td><td>{a.actorLabel ?? 'system'}</td><td><Badge>{a.action}</Badge></td><td className="text-xs text-muted">{a.entityType} {a.entityId?.slice(0, 8)}</td><td className="max-w-md truncate text-xs text-muted" title={JSON.stringify({ old: a.oldValue, new: a.newValue }, null, 1)}>{a.newValue ? JSON.stringify(a.newValue).slice(0, 140) : a.oldValue ? `was ${JSON.stringify(a.oldValue).slice(0, 100)}` : '—'}</td><td className="text-muted">{a.reason ?? '—'}</td><td className="text-xs text-muted">{a.ipAddress ?? '—'}</td></tr>)}</tbody></table></div>}{audit.data && <Pagination page={audit.data.meta.page} totalPages={audit.data.meta.totalPages} total={audit.data.meta.total} onPage={(p) => setF({ ...f, page: p })} />}</Card>}
      {tab === 'integrations' && <div className="grid gap-4 lg:grid-cols-2"><Card title="Recent integration logs" padded={false}><table className="data"><thead><tr><th>When</th><th>Operation</th><th>Status</th><th>ms</th></tr></thead><tbody>{logs.data?.logs.map((l: any) => <tr key={l.id}><td>{fmtDateTime(l.createdAt)}</td><td>{l.operation}</td><td><Badge status={l.status === 'SUCCESS' ? 'DONE' : 'ERROR'}>{l.status}</Badge></td><td>{l.durationMs ?? '—'}</td></tr>)}</tbody></table>{logs.data?.logs.length === 0 && <EmptyState title="No integration activity" />}</Card><Card title="Open failures (dead letter)" padded={false}><table className="data"><thead><tr><th>When</th><th>Operation</th><th>Error</th><th>Attempts</th></tr></thead><tbody>{logs.data?.failures.map((l: any) => <tr key={l.id}><td>{fmtDateTime(l.createdAt)}</td><td>{l.operation}</td><td className="max-w-xs truncate text-danger">{l.error}</td><td>{l.attempts}</td></tr>)}</tbody></table>{logs.data?.failures.length === 0 && <EmptyState title="No failures" />}</Card></div>}
      {tab === 'workflows' && <div className="grid gap-4 md:grid-cols-2">{wf.data?.map((w) => <Card key={w.id} title={<span>{w.name} <span className="text-xs text-muted">v{w.version} · {w.entityType}</span></span>} actions={<Badge status={w.isActive ? 'ACTIVE' : 'CANCELLED'}>{w.isActive ? 'active' : 'inactive'}</Badge>}><ol className="space-y-1.5">{(w.steps as any[]).map((s, i) => <li key={s.key} className="flex items-center gap-2 text-sm"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-surface-2 text-[11px] font-semibold">{i + 1}</span><span className="font-medium">{s.key}</span><span className="text-xs text-muted">{s.approverType}{s.roleCode ? ` · ${s.roleCode.replace(/_/g, ' ')}` : ''}{s.condition ? ` · if ${s.condition.field} ${s.condition.op} ${s.condition.value}` : ''}</span></li>)}</ol></Card>)}</div>}
      {tab === 'recon' && (recon.data ? <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-3 xl:grid-cols-6">{Object.entries(recon.data.summary).map(([k, v]) => <div key={k} className="card p-4"><p className="text-[11px] uppercase tracking-wider text-muted">{k.replace(/([A-Z])/g, ' $1')}</p><p className={`text-2xl font-semibold ${(v as number) > 0 ? 'text-warning' : 'text-success'}`}>{v as number}</p></div>)}</div><Card title={`Findings · ${recon.data.periodStart} → ${recon.data.periodEnd} · ${fmtDateTime(recon.data.createdAt)}`} padded={false}>{recon.data.findings.length ? <table className="data"><thead><tr><th>Type</th><th>Detail</th></tr></thead><tbody>{recon.data.findings.map((f: any, i: number) => <tr key={i}><td><Badge status="MEDIUM">{f.type}</Badge></td><td className="text-xs text-muted">{JSON.stringify(f)}</td></tr>)}</tbody></table> : <EmptyState title="No mismatches" />}</Card></div> : <EmptyState title="No reconciliation run yet" hint="Runs nightly, or trigger from Attendance → Recalculate." />)}
    </>
  );
}
