'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus } from 'lucide-react';
import { AppShell } from '@/components/layout/shell';
import { api, qs } from '@/lib/api';
import { useAuth } from '@/lib/providers';
import { Badge, Card, EmptyState, Field, Modal, PageHeader, StatTile, Tabs, TableSkeleton } from '@/components/ui';
import { fmtDate, fmtMoney, humanStatus } from '@/lib/format';

export default function Page() { return <AppShell><Training /></AppShell>; }
type Tab = 'records' | 'catalog';

function Training() {
  const { can } = useAuth();
  const sp = useSearchParams();
  const qc = useQueryClient();
  const [tab, setTab] = useState<Tab>('records');
  const [f, setF] = useState({ status: '', expiring: sp.get('expiring') === '1' });
  const records = useQuery({ queryKey: ['training', 'records', f], queryFn: () => api<any[]>(`/api/v1/people/training/records${qs({ status: f.status, expiring: f.expiring || undefined })}`) });
  const catalog = useQuery({ queryKey: ['training', 'catalog'], queryFn: () => api<any[]>('/api/v1/people/training/catalog') });
  const [edit, setEdit] = useState<any | null>(null);
  const [course, setCourse] = useState<any | null>(null);
  const inv = () => qc.invalidateQueries({ queryKey: ['training'] });
  const save = useMutation({ mutationFn: () => api(`/api/v1/people/training/records/${edit.id}`, { method: 'PATCH', json: { status: edit.status, completedAt: edit.completedAt || undefined, score: edit.score === '' ? null : Number(edit.score), certificateNo: edit.certificateNo || null, certificateExpiry: edit.certificateExpiry || null, cost: edit.cost === '' ? null : Number(edit.cost), notes: edit.notes || null } }), onSuccess: () => { setEdit(null); inv(); } });
  const saveCourse = useMutation({ mutationFn: () => api('/api/v1/people/training/catalog', { method: 'POST', json: { ...course, durationHours: course.durationHours === '' ? null : Number(course.durationHours), validityMonths: course.validityMonths === '' ? null : Number(course.validityMonths) } }), onSuccess: () => { setCourse(null); inv(); } });
  const rows = records.data ?? [];
  const expiring = rows.filter((r) => r.expiryStatus === 'EXPIRING' || r.expiryStatus === 'EXPIRED').length;
  return (
    <>
      <PageHeader eyebrow="Talent" title="Training & certifications" subtitle="Assign courses, record completion and scores, and track certificate expiry (safety inductions, work-at-height, first aid…)." actions={can('training:write') && tab === 'catalog' && <button className="btn-primary" onClick={() => setCourse({ code: '', title: '', category: 'HSE', provider: '', durationHours: '', validityMonths: '', isMandatory: false })}><Plus size={16} />Course</button>} />
      <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatTile label="Records" value={records.data?.length ?? '—'} /><StatTile label="Planned / in progress" value={rows.filter((r) => ['PLANNED', 'ASSIGNED', 'IN_PROGRESS'].includes(r.status)).length} tone="info" /><StatTile label="Completed" value={rows.filter((r) => r.status === 'COMPLETED').length} tone="success" /><StatTile label="Certificates expiring / expired" value={expiring} tone={expiring ? 'warning' : 'default'} /></div>
      <Tabs tabs={[{ key: 'records', label: 'Records' }, { key: 'catalog', label: 'Catalog', count: catalog.data?.length }]} value={tab} onChange={setTab} />
      {tab === 'records' && <Card padded={false} actions={<><select className="input sm:w-44" value={f.status} onChange={(e) => setF({ ...f, status: e.target.value })}><option value="">All statuses</option>{['PLANNED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED'].map((s) => <option key={s} value={s}>{humanStatus(s)}</option>)}</select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={f.expiring} onChange={(e) => setF({ ...f, expiring: e.target.checked })} />Expiring only</label></>} title="Training records">
        {records.isLoading ? <TableSkeleton /> : rows.length ? <div className="overflow-x-auto"><table className="data"><thead><tr><th>Employee</th><th>Course</th><th>Scheduled</th><th>Completed</th><th>Score</th><th>Certificate</th><th>Expiry</th><th>Status</th><th></th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td><Link href={`/employees/${r.employeeId}?tab=training`} className="font-medium hover:underline">{r.employeeName}</Link><span className="block text-[11px] text-muted">{r.employeeNo}</span></td><td>{r.title}<span className="block text-[11px] text-muted">{r.code} · {humanStatus(r.category)}</span></td><td>{fmtDate(r.scheduledDate)}</td><td>{fmtDate(r.completedAt)}</td><td>{r.score ?? '—'}</td><td>{r.certificateNo ?? '—'}</td><td>{r.certificateExpiry ? <span className="inline-flex items-center gap-2">{fmtDate(r.certificateExpiry)}{r.expiryStatus && <Badge status={r.expiryStatus} />}</span> : '—'}</td><td><Badge status={r.status} /></td><td>{can('training:write') && <button className="btn-ghost btn-sm" onClick={() => setEdit({ id: r.id, status: r.status, completedAt: r.completedAt ?? '', score: r.score ?? '', certificateNo: r.certificateNo ?? '', certificateExpiry: r.certificateExpiry ?? '', cost: r.cost ?? '', notes: r.notes ?? '' })}>Update</button>}</td></tr>)}</tbody></table></div> : <EmptyState hint="Assign training from an employee profile (Actions → Assign training) or in bulk from the directory." />}
      </Card>}
      {tab === 'catalog' && <Card padded={false} title="Course catalog">{catalog.data?.length ? <table className="data"><thead><tr><th>Code</th><th>Title</th><th>Category</th><th>Provider</th><th>Hours</th><th>Validity</th><th>Mandatory</th><th>Completed</th></tr></thead><tbody>{catalog.data.map((c) => <tr key={c.id}><td className="font-mono text-xs">{c.code}</td><td className="font-medium">{c.title}</td><td>{humanStatus(c.category)}</td><td>{c.provider ?? '—'}</td><td>{c.durationHours ?? '—'}</td><td>{c.validityMonths ? `${c.validityMonths} months` : 'No expiry'}</td><td>{c.isMandatory ? <Badge status="HIGH" dot={false}>Mandatory</Badge> : '—'}</td><td>{c.completed ?? c.completedCount ?? '—'}</td></tr>)}</tbody></table> : <EmptyState />}</Card>}
      <Modal open={!!edit} onClose={() => setEdit(null)} title="Update training record">{edit && <div className="grid gap-3 sm:grid-cols-2"><Field label="Status"><select className="input" value={edit.status} onChange={(e) => setEdit({ ...edit, status: e.target.value })}>{['ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED'].map((s) => <option key={s} value={s}>{humanStatus(s)}</option>)}</select></Field><Field label="Completed on"><input type="date" className="input" value={edit.completedAt} onChange={(e) => setEdit({ ...edit, completedAt: e.target.value })} /></Field><Field label="Score"><input type="number" className="input" value={edit.score} onChange={(e) => setEdit({ ...edit, score: e.target.value })} /></Field><Field label="Cost (AED)"><input type="number" className="input" value={edit.cost} onChange={(e) => setEdit({ ...edit, cost: e.target.value })} /></Field><Field label="Certificate no."><input className="input" value={edit.certificateNo} onChange={(e) => setEdit({ ...edit, certificateNo: e.target.value })} /></Field><Field label="Certificate expiry" hint="Left blank: computed from the course validity"><input type="date" className="input" value={edit.certificateExpiry} onChange={(e) => setEdit({ ...edit, certificateExpiry: e.target.value })} /></Field><Field label="Notes" className="sm:col-span-2"><input className="input" value={edit.notes} onChange={(e) => setEdit({ ...edit, notes: e.target.value })} /></Field><div className="flex justify-end sm:col-span-2"><button className="btn-primary" onClick={() => save.mutate()}>Save</button></div></div>}</Modal>
      <Modal open={!!course} onClose={() => setCourse(null)} title="New course">{course && <div className="grid gap-3 sm:grid-cols-2"><Field label="Code"><input className="input" value={course.code} onChange={(e) => setCourse({ ...course, code: e.target.value.toUpperCase() })} /></Field><Field label="Category"><input className="input" value={course.category} onChange={(e) => setCourse({ ...course, category: e.target.value.toUpperCase() })} /></Field><Field label="Title" className="sm:col-span-2"><input className="input" value={course.title} onChange={(e) => setCourse({ ...course, title: e.target.value })} /></Field><Field label="Provider"><input className="input" value={course.provider} onChange={(e) => setCourse({ ...course, provider: e.target.value })} /></Field><Field label="Duration (hours)"><input type="number" className="input" value={course.durationHours} onChange={(e) => setCourse({ ...course, durationHours: e.target.value })} /></Field><Field label="Certificate validity (months)"><input type="number" className="input" value={course.validityMonths} onChange={(e) => setCourse({ ...course, validityMonths: e.target.value })} /></Field><label className="flex items-center gap-2 self-end text-sm"><input type="checkbox" checked={course.isMandatory} onChange={(e) => setCourse({ ...course, isMandatory: e.target.checked })} />Mandatory</label><div className="flex justify-end sm:col-span-2"><button className="btn-primary" disabled={!course.code || !course.title} onClick={() => saveCourse.mutate()}>Save</button></div></div>}</Modal>
      <span className="hidden">{fmtMoney(0)}</span>
    </>
  );
}
